### ISSUE TITLE
ScriptServiceUtil not initialized yet on startup

### ISSUE THREAD

**Issue by sjka** [eclipse/smarthome#3562]
```
2017-05-31 20:09:57.118 [ERROR] [xbase.resource.BatchLinkableResource] - resolution of uriFragment '|::0.2.1.2.0.1.2.2.2.0.6.6.6::0::/1' failed.
java.lang.IllegalStateException: ScriptServiceUtil not initialized yet!
        at org.eclipse.smarthome.model.script.ScriptServiceUtil.getInstance(ScriptServiceUtil.java:88)
        at org.eclipse.smarthome.model.script.ScriptServiceUtil.getActionServices(ScriptServiceUtil.java:114)
        at org.eclipse.smarthome.model.script.internal.engine.ServiceTrackerActionServiceProvider.get(ServiceTrackerActionServiceProvider.java:21)
        at org.eclipse.smarthome.model.script.internal.engine.ServiceTrackerActionServiceProvider.get(ServiceTrackerActionServiceProvider.java:1)
        at org.eclipse.smarthome.model.script.scoping.ScriptImplicitlyImportedTypes.getActionClasses(ScriptImplicitlyImportedTypes.java:100)
        at org.eclipse.smarthome.model.script.scoping.ScriptImplicitlyImportedTypes.getStaticImportClasses(ScriptImplicitlyImportedTypes.java:94)
        at org.eclipse.xtext.xbase.scoping.batch.ImplicitlyImportedFeatures.getStaticImportClasses(ImplicitlyImportedFeatures.java:66)
        at org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider.newSession(XbaseBatchScopeProvider.java:112)
        at org.eclipse.xtext.xbase.typesystem.internal.DefaultReentrantTypeResolver.resolve(DefaultReentrantTypeResolver.java:162)
        at org.eclipse.xtext.xbase.typesystem.internal.DefaultReentrantTypeResolver.reentrantResolve(DefaultReentrantTypeResolver.java:139)
        at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$LazyResolvedTypes.resolveTypes(CachingBatchTypeResolver.java:80)
        at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$2.process(CachingBatchTypeResolver.java:57)
        at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver$2.process(CachingBatchTypeResolver.java:1)
        at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
        at org.eclipse.xtext.util.OnChangeEvictingCache.execWithoutCacheClear(OnChangeEvictingCache.java:129)
        at org.eclipse.xtext.xbase.typesystem.internal.CachingBatchTypeResolver.doResolveTypes(CachingBatchTypeResolver.java:53)
        at org.eclipse.xtext.xbase.typesystem.internal.AbstractBatchTypeResolver.resolveTypes(AbstractBatchTypeResolver.java:69)
        at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:60)
        at org.eclipse.xtext.xbase.resource.BatchLinkingService.resolveBatched(BatchLinkingService.java:41)
        at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getEObject(BatchLinkableResource.java:117)
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
        at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:203)
        at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:259)
        at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1477)
        at org.eclipse.xtext.xbase.impl.XAbstractFeatureCallImplCustom.getFeature(XAbstractFeatureCallImplCustom.java:48)
        at org.eclipse.xtext.xbase.validation.XbaseValidator.checkDelegateConstructorIsFirst(XbaseValidator.java:927)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_131]
        at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:118)[142:org.eclipse.xtext:2.9.2]
        at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:312)[142:org.eclipse.xtext:2.9.2]
        at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71)[142:org.eclipse.xtext:2.9.2]
        at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:151)[142:org.eclipse.xtext:2.9.2]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:108)[65:org.eclipse.emf.ecore:2.11.1.v20150805-0538]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.validateModel(ModelRepositoryImpl.java:265)[123:org.eclipse.smarthome.model.core:0.9.0.201705301617]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:90)[123:org.eclipse.smarthome.model.core:0.9.0.201705301617]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:244)[123:org.eclipse.smarthome.model.core:0.9.0.201705301617]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.notifyUpdateToModelRepo(FolderObserver.java:170)[123:org.eclipse.smarthome.model.core:0.9.0.201705301617]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.updated(FolderObserver.java:148)[123:org.eclipse.smarthome.model.core:0.9.0.201705301617]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[3:org.apache.felix.configadmin:1.8.12]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[3:org.apache.felix.configadmin:1.8.12]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[3:org.apache.felix.configadmin:1.8.12]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1461)[3:org.apache.felix.configadmin:1.8.12]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1417)[3:org.apache.felix.configadmin:1.8.12]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141)[3:org.apache.felix.configadmin:1.8.12]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109)[3:org.apache.felix.configadmin:1.8.12]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]

```

See https://community.openhab.org/t/snapshot-930-not-starting-properly/29252

**Comment by sjka** [comment]
Just found the root-cause, will create a PR asap

**Comment by sjka** [comment]
The stacktrace came in via `ModelRepositoryImpl`. This class would never ever tried to load (& validate) a model, it the respective `ModelParser` was not there. However, the rule-`ModelParser` didn't give a s**t whether the scripts stuff is available or not (although the whole rules stuff is nothing else than a few scripts plus some triggers. Hence adding this simply static dependency should fix it.

**Comment by shorty707** [comment]
this issues still exists with the most current build

can not confirm this is solved! @sjka @kaikreuzer

**Comment by shorty707** [comment]
build 938 is the one I have problems with

**Comment by mherwege** [comment]
I have the same problem with build 938.

**Comment by sjka** [comment]
@mherwege good that your home is working right now - the rest of course does not sound so well...
Would you happen to have the full stacktraces from one of your huge logs? The problem here is not that the ScriptServiceUtil is being _used_ at different places (they are easy to find), it's rather that the rules and script files should not have been read at all while the ScriptServiceUtil is not ready. So I need to figure out the entry point which is living its own life and is the root-cause for this whole mess... So although they are ugly to read here, it would be really helpful to have them.

**Comment by mherwege** [comment]
@sjka Here are two log files. The first one is the failed start. I only provided the first 5Mb, but the following 85Mb are a continuous repeat. If you need them all, we should find another way of sending them. The second file is the startup after cleaning temp and cache until my system is up and stable. At the end I tried a few switches through Basic UI that got executed well. The same error is still in but does not get repeated eternally anymore.
[openhab_log_startup1.txt](https://github.com/eclipse/smarthome/files/1057175/openhab_log_startup1.txt)
[openhab_log_startup2.txt](https://github.com/eclipse/smarthome/files/1057183/openhab_log_startup2.txt)

**Comment by sjka** [comment]
> I only provided the first 5Mb, but the following 85Mb are a continuous repeat. If you need them all, we should find another way of sending them.

Perfect! That'll do... 
Thanks for the quick response!

**Comment by kaikreuzer** [comment]
FTR: The latest openHAB distro 939 contains @sjka's latest changes - so time to do some new testing with

```
log:set DEBUG org.eclipse.smarthome.model.core
```

**Comment by sjka** [comment]
Minor correction, we need the script logs too, so for testing please use these here:

```
log:set DEBUG org.eclipse.smarthome.model.core
log:set DEBUG org.eclipse.smarthome.model.script
```

**Comment by mherwege** [comment]
Damn, I was too quick. I did the upgrade only with the core debug enabled. The error appeared, although the upgrade was much smoother then yesterday. So no 85Mb log spam.
I then restarted the service with both debug lines enabled, and the error did not show up anymore. It looks like we are out of luck catching this one.
If it still helps, I have attached both debug logs of the full start again. Log 3 is the start after the upgrade. Log 4 is the restart with the additional debug configuration.
[openhab_log_startup3.txt](https://github.com/eclipse/smarthome/files/1058420/openhab_log_startup3.txt)
[openhab_log_startup4.txt](https://github.com/eclipse/smarthome/files/1058421/openhab_log_startup4.txt)

**Comment by kaikreuzer** [comment]
Note that the it is (unfortunately) "normal" that directly after the update there are many errors in the log - this is definitely unrelated to this issue here.

So I count it as a good sign that you say that the issue does not occur on subsequent restarts anymore. Does it mean that the distro starts all fine and is fully usable?

**Comment by mherwege** [comment]
I am aware of the "normal issue" after an update. I can confirm that this build did start and is fully usable, immediately after the update and on a subsequent restart. The error only appeared just after the update this time and was only triggered a limited number of times.
So it looks all good for now. I will keep watching this on future updates.

**Comment by jurviz** [comment]
I have just tried to upgrade from a running build #938 to the latest build.
I have the same symptoms again. Last time a did a purge and reinstall to get a running build #938.
The system does not startup successfully after a bunch of exceptions.
I can provide logs if needed.

**Comment by sjka** [comment]
> I can provide logs if needed.

Yes, please with both DEBUGs enabled:

```
log:set DEBUG org.eclipse.smarthome.model.core
log:set DEBUG org.eclipse.smarthome.model.script
```

**Comment by jurviz** [comment]
openhab is currently stopped. How can i set the logs before starting again?

**Comment by kaikreuzer** [comment]
Start it, set the log levels and stop it again :-)

**Comment by jurviz** [comment]
I have started openhab, but i can't get a karaf console connection to set the log level.
These are the messages from openhab.log:
2017-06-07 22:51:48.677 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
2017-06-07 22:51:48.715 [ERROR] [org.openhab.binding.jeelink         ] - FrameworkEvent ERROR - org.openhab.binding.jeelink
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.jeelink [9]
  Unresolved requirement: Import-Package: gnu.io

        at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
2017-06-07 22:52:01.596 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
2017-06-07 22:52:02.728 [INFO ] [persistence.jdbc.internal.JdbcMapper] - JDBC::openConnection: Driver is available::Yank setupDataSource
2017-06-07 22:52:03.675 [INFO ] [ui.habmin.internal.servlet.HABminApp] - Started HABmin servlet at /habmin
2017-06-07 22:52:03.763 [INFO ] [panel.internal.HABPanelDashboardTile] - Started HABPanel at /habpanel
2017-06-07 22:52:07.260 [INFO ] [el.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'fernholz.rules', using it anyway:
The use of wildcard imports is deprecated.
2017-06-07 22:52:07.274 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'fernholz.rules'
2017-06-07 22:52:08.187 [INFO ] [el.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'weather.rules', using it anyway:
The use of wildcard imports is deprecated.
2017-06-07 22:52:08.195 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'weather.rules'
2017-06-07 22:52:08.257 [INFO ] [egram.internal.TelegramActionService] - Bot homebot loaded from config file
2017-06-07 22:52:08.269 [INFO ] [penhab.io.transport.mqtt.MqttService] - MQTT Service initialization completed.
2017-06-07 22:52:08.271 [INFO ] [t.mqtt.internal.MqttBrokerConnection] - Starting MQTT broker connection 'mosquitto'

Despite the message paperui ist started, i cannot use the ui.

"NetworkError: 404 Not Found - http://pine64.fritz.box/rest/events"
events
"NetworkError: 404 Not Found - http://pine64.fritz.box/rest/links/auto"
auto
"NetworkError: 404 Not Found - http://pine64.fritz.box/rest/inbox"
inbox
"NetworkError: 404 Not Found - http://pine64.fritz.box/rest/bindings"
bindings
"NetworkError: 404 Not Found - http://pine64.fritz.box/rest"
rest
"NetworkError: 404 Not Found - http://pine64.fritz.box/rest/inbox"
inbox
"NetworkError: 404 Not Found - http://pine64.fritz.box/rest/thing-types"
thing-types
Firefox can’t establish a connection to the server at http://pine64.fritz.box/rest/events.
	

services.min.js (line 1, col 20276)
"NetworkError: 404 Not Found - http://pine64.fritz.box/rest/events"
events
Firefox can’t establish a connection to the server at http://pine64.fritz.box/rest/events.
	

services.min.js (line 1, col 20276)
"NetworkError: 404 Not Found - http://pine64.fritz.box/rest/events"
events
Firefox can’t establish a connection to the server at http://pine64.fritz.box/rest/events.
	

services.min.js (line 1, col 20276)
"NetworkError: 404 Not Found - http://pine64.fritz.box/rest/events"
events
Firefox can’t establish a connection to the server at http://pine64.fritz.box/rest/events.
	

services.min.js (line 1, col 20276)
"NetworkError: 404 Not Found - http://pine64.fritz.box/rest/events"
events
Firefox can’t establish a connection to the server at http://pine64.fritz.box/rest/events.
	

services.min.js (line 1, col 20276)
"NetworkError: 404 Not Found - http://pine64.fritz.box/rest/events"
events
Firefox can’t establish a connection to the server at http://pine64.fritz.box/rest/events.
	

services.min.js (line 1, col 20276)
"NetworkError: 404 Not Found - http://pine64.fritz.box/rest/events"
events
Firefox can’t establish a connection to the server at http://pine64.fritz.box/rest/events.

basicui and classicui are not started.

**Comment by jurviz** [comment]
The system is now in an unusable state.

**Comment by jurviz** [comment]
I had to purge installation and reinstall to get it running again.
Build #939 is now active.
