### ISSUE TITLE
Group Operator Count does not work as expected

### ISSUE THREAD

**Issue by clinique** [eclipse/smarthome#4460]
I saw that group operator count was not documented.
Per comments it is expected to work this way : 
```
* Group:Number:COUNT(".") will count all items having a string state of one character
* Group:Number:COUNT("[5-9]") will count all items having a string state between 5 and 9
```

So I was about to give him some unit tests but I face an issue : 
- Per global logic (in ItemDTOMapper.mapFunction) group operators that accepts arguments are expected to return the same type than the operator but this does not work for Count as the operator is StringType while output is DecimalType.
I don't know how this happened to work on OH1 but ESH complains : 

Definition : 
```
Group:String:COUNT(".*") gSensorAirq	"Qualité Air [%d]"	<airquality>	(gSensors)


2017-10-27 08:00:24.128 [ERROR] [pse.smarthome.core.items.GenericItem] - Tried to set invalid state 5 (DecimalType) on item gSensorAirq of type StringItem, ignoring it
```
but value of the group seems good.

If I switch definition to Number : 
```
Group:Number:COUNT(".*") gSensorAirq	"Qualité Air [%d]"	<airquality>	(gSensors)

2017-10-27 09:45:05.068 [WARN ] [arthome.core.items.dto.ItemDTOMapper] - State '.*' is not valid for a group item with base type 'Number'
```

while changing label value format to %s :
```
Group:String:COUNT(".*") gSensorAirq	"Qualité Air [%s]"	<airquality>	(gSensors)
```
does not log error and does not work at all.

Has somebody an idea on how to address this ?

**Comment by maggu2810** [comment]
> Has somebody an idea on how to address this ?

Sorry, I am not using the COUNT group type and never used it. So I have no idea about it. Perhaps some one that uses it can give some information.

**Comment by kaikreuzer** [comment]
Sorry, I also have never had a deeper look into the COUNT function.
@triller-telekom refactored a few things in ESH to deal with accepted types etc., so that might have caused something to break that once worked on OH1.

**Comment by triller-telekom** [comment]
The code in `ItemDTOMapper.mapFunction` that checks the types is part of ESH and thus it was never part of OH1. So this explains why this might work there...

This definition
```
Group:String:COUNT(".*") gSensorAirq	"Qualité Air [%d]"	<airquality>	(gSensors)
```

is clearly wrong because a count never returns type `String` but it returns a `DecimalType`, so this is the correct definition:

```
Group:Number:COUNT(".*") gSensorAirq	"Qualité Air [%d]"	<airquality>	(gSensors)
```

The reason why this was not working is that the check for types is correct for AND, NAND, OR and NOR, but not for COUNT. I have fixed that in #4523 by passing a `StringType` to the COUNT function. So the correct definition of the group with `Number` is working now.

**Comment by staehler** [comment]
Sorry for reopening, but I face a warning when I use this group item, which counts closed shutters (regex: count all items with state != 0)

    Group:Number:COUNT("^[1-9]*$") gRollo "Rollos [(%d)]"

All my shutters belong to the group gRollo. It sems, that the group count is correct, but I get this warning:

    2019-01-05 10:22:01.261 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'gruppen.items'
    2019-01-05 10:22:01.269 [WARN ] [arthome.core.items.dto.ItemDTOMapper] - State '^[1-9]*$' is not valid for a group item with base type 'Number'

The event.log shows a correct handling:

    2019-01-05 10:22:38.017 [GroupItemStateChangedEvent] - gRollo changed from 0 to 1 through RolloGalerie

I'm going to ingore the warning, but could someone explain, what happens here? Is this my fault or is there a bug?

I use openhab2 2.5.0~S1479-1 on debian stretch.

**Comment by c--r** [comment]
Hi, I have observed the same error on Openhab 2.4.0

**Comment by doits** [comment]
Seeing the same be behavior for counting open contacts:

```
Group:Number:COUNT("OPEN") gContacts "Open Contacts [%d]"

# [WARN ] [arthome.core.items.dto.ItemDTOMapper] - State 'OPEN' is not valid for a group item with base type 'Number'
```

It counts correctly, so maybe just ignore the warning ...

**Comment by Hobohome** [comment]
This warning message still exists in 2.5.4. It seems to me that the problem is that the type of perimeter (in this case "open") is being evaluated for type when the returned value will always be a number. 
The warning should be generated if the type is NOT one able to receive a numeric value. 
A simple fix?
