### ISSUE TITLE
BUG: ExtendedDiscoveryService implementation can cause null pointer access

### ISSUE THREAD

**Issue by mgeramb** [eclipse/smarthome#5568]
The implementation of the ExtendedDiscoveryService has a major timing problem. I have implemented a discovery service in my amazonechobinding. 
Sometimes the function  DiscoveryServiceRegistryImpl.addDiscoveryService will be called with my extended discovery service before the safeCaller get injected.

I suggest, that if the safeCaller is not yet set, it should be ignored and extended discovery services should be called in the setSafeCaller for all already registered services.

**Comment by sjka** [comment]
My assumption is that this was fixed with #4766. 
Which version are you running on?

**Comment by mgeramb** [comment]
I run it from the the eclipse. The repository is a from 29.12.1017 commit 81c2d771a53623a7fb4f600e906b4fad79f3b1e7. This is after the #4766 merge

Currently if have implement a workaround so that the discoverservice is not automatically created through the OSGI. This works for me, but it should be fixed, because other developers will fall in the same issue.

**Comment by kaikreuzer** [comment]
>  The repository is a from 29.12.1017

Why? You should urgently go to a more recent version as you might see all kinds of unexpected behaviour otherwise.

**Comment by mgeramb** [comment]
> Why
Because if have to build a 2.2 version of my binding for the community. And this seem to be the easiest way for me. For the addon repository if have created a branch. I know I can switch the other repositories, but currently I have no problem or unexpected behaviours.

**Comment by kaikreuzer** [comment]
Ok, thanks, that makes sense indeed. So time for the 2.3 release then :-)
But I'd nonetheless suggest that you retest this bug on the latest ESH code to make sure it still exists - this isn't urgent, so I'd suggest to close it meanwhile and you can re-open it any time when you can confirm that it is still an issue.
