### ISSUE TITLE
openhab 2: Bose Soundtouch Binding: NullPointerException with source 'ALEXA or "PRODUCT" 

### ISSUE THREAD

**Issue by zr2002** [eclipse/smarthome#5638]
On every change of a song title with the source 'ALEXA or "PRODUCT" I get an error in openhab2.log. In Paper UI the "Item Name" is in both cases "undefined".
If I use another sources like TuneIn or Deezer the error does not occur and the "Item Name" contains entries.  I don't know if this is relevant.

`2018-05-26 14:14:27.098 [ERROR] [dtouch.handler.BoseSoundTouchHandler] - Wohnzimmer SoundTouch 300: Could not parse XML from string '<updates deviceID="XXX"><nowPlayingUpdated><nowPlaying deviceID="XXX" source="PRODUCT" sourceAccount="TV"><ContentItem source="PRODUCT" sourceAccount="TV" isPresetable="false" /><art artImageStatus="SHOW_DEFAULT_IMAGE" /><playStatus>PLAY_STATE</playStatus></nowPlaying></nowPlayingUpdated></updates>'; exception is: `

java.lang.NullPointerException: null

	at org.openhab.binding.bosesoundtouch.internal.ContentItem.isValid(ContentItem.java:70) [234:org.openhab.binding.bosesoundtouch:2.3.0.201803251745]

***
OR
***
`2018-05-26 14:48:03.144 [ERROR] [dtouch.handler.BoseSoundTouchHandler] - Buero: Could not parse XML from string '<updates deviceID="XXX"><nowPlayingUpdated><nowPlaying deviceID="XXX" source="ALEXA" sourceAccount=""><ContentItem source="ALEXA" type="tracklisturl" location="DO_NOT_RESUME" sourceAccount="" isPresetable="false"><itemName></itemName></ContentItem><track>Alexa</track><artist></artist><album></album><stationName></stationName><art artImageStatus="SHOW_DEFAULT_IMAGE" /><time total="0">60</time><skipEnabled /><playStatus>PLAY_STATE</playStatus><skipPreviousSupported value="false" /><seekSupported value="true" /><streamType>RADIO_TRACKS</streamType></nowPlaying></nowPlayingUpdated></updates>'; exception is:`

java.lang.NullPointerException: null
	at org.openhab.binding.bosesoundtouch.internal.ContentItem.isValid(ContentItem.java:70) [234:org.openhab.binding.bosesoundtouch:2.3.0.201803251745]

	at org.openhab.binding.bosesoundtouch.internal.CommandExecutor.setCurrentContentItem(CommandExecutor.java:131) [234:org.openhab.binding.bosesoundtouch:2.3.0.201803251745]

	at org.openhab.binding.bosesoundtouch.internal.XMLResponseHandler.endElement(XMLResponseHandler.java:385) [234:org.openhab.binding.bosesoundtouch:2.3.0.201803251745]

	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) [?:?]

	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841) [?:?]

	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770) [?:?]

	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) [?:?]

	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) [?:?]

	at org.openhab.binding.bosesoundtouch.internal.XMLResponseProcessor.handleMessage(XMLResponseProcessor.java:41) [234:org.openhab.binding.bosesoundtouch:2.3.0.201803251745]

	at org.openhab.binding.bosesoundtouch.handler.BoseSoundTouchHandler.onWebSocketText(BoseSoundTouchHandler.java:400) [234:org.openhab.binding.bosesoundtouch:2.3.0.201803251745]

	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:189) [99:org.eclipse.jetty.websocket.common:9.3.22.v20171030]

	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69) [99:org.eclipse.jetty.websocket.common:9.3.22.v20171030]

	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66) [99:org.eclipse.jetty.websocket.common:9.3.22.v20171030]

	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:158) [99:org.eclipse.jetty.websocket.common:9.3.22.v20171030]

	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162) [99:org.eclipse.jetty.websocket.common:9.3.22.v20171030]

	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376) [99:org.eclipse.jetty.websocket.common:9.3.22.v20171030]

	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220) [99:org.eclipse.jetty.websocket.common:9.3.22.v20171030]

	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220) [99:org.eclipse.jetty.websocket.common:9.3.22.v20171030]

	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256) [99:org.eclipse.jetty.websocket.common:9.3.22.v20171030]

	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679) [99:org.eclipse.jetty.websocket.common:9.3.22.v20171030]

	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511) [99:org.eclipse.jetty.websocket.common:9.3.22.v20171030]

	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [83:org.eclipse.jetty.io:9.3.22.v20171030]

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [83:org.eclipse.jetty.io:9.3.22.v20171030]

	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [83:org.eclipse.jetty.io:9.3.22.v20171030]

	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [94:org.eclipse.jetty.util:9.3.22.v20171030]

	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [94:org.eclipse.jetty.util:9.3.22.v20171030]

	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [94:org.eclipse.jetty.util:9.3.22.v20171030]

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [94:org.eclipse.jetty.util:9.3.22.v20171030]

	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [94:org.eclipse.jetty.util:9.3.22.v20171030]

	at java.lang.Thread.run(Thread.java:748) [?:?]

==> /var/log/openhab2/events.log <==

2018-05-26 14:46:25.188 [vent.ItemStateChangedEvent] - BoseSt10_1_nowPlayingItemName changed from null to 

2018-05-26 14:46:25.219 [vent.ItemStateChangedEvent] - BoseSt10_1_nowPlayingItemName changed from  to null

![image](https://user-images.githubusercontent.com/36036468/40576255-0f94daa2-60f3-11e8-8309-9e5dc838bfcb.png)

**Comment by kaikreuzer** [comment]
> org.openhab.binding.bosesoundtouch:2.3.0.201803251745

@zr2002 This binding is only in ESH since April 24, so you seem to use some unofficial early build.

Could you please re-test with the current code and post the log files if the problem occurs there as well?

**Comment by kaikreuzer** [comment]
@tratho Might this be related to / fixed with https://github.com/eclipse/smarthome/pull/5639 as well?

**Comment by zr2002** [comment]
I have spent last sunday to compile the ESH binding, unfortunately it doesn't work (for me and my skills). I didn't find the precompiled jar-binding, so I have to wait for the next version. I apologize for the inconvenience.

**Comment by tratho** [comment]
@kaikreuzer i think you can close this!
primarily because it's the old, the wrong binding.

**Comment by zr2002** [comment]
I upgraded my system to the new openhab 2.3.0 stable and installed the Bose binding via PaperUI. The warning still occurs.


![image](https://user-images.githubusercontent.com/36036468/40775371-3204aa80-64c8-11e8-9e3a-cec141f65748.png)
If I use another sources like TuneIn or Deezer the error does not occur and the "Item Name" contains entries.


`2018-05-31 11:23:05.545 [WARN ] [dtouch.handler.BoseSoundTouchHandler] - Wohnzimmer SoundTouch 300: Could not parse XML from string <?xml version="1.0" encoding="UTF-8" ?><msg><header deviceID="XXX" url="now_playing" method="GET"><request requestID="0" msgType="RESPONSE"><info type="new" /></request></header><body><nowPlaying deviceID="9884E3A1D286" source="PRODUCT" sourceAccount="TV"><ContentItem source="PRODUCT" sourceAccount="TV" isPresetable="false" /><art artImageStatus="SHOW_DEFAULT_IMAGE" /><playStatus>PLAY_STATE</playStatus></nowPlaying></body></msg>'.`

java.lang.NullPointerException: null

	at org.eclipse.smarthome.binding.bosesoundtouch.internal.ContentItem.isValid(ContentItem.java:74) [233:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]

	at org.eclipse.smarthome.binding.bosesoundtouch.internal.CommandExecutor.setCurrentContentItem(CommandExecutor.java:114) [233:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]

	at org.eclipse.smarthome.binding.bosesoundtouch.internal.XMLResponseHandler.endElement(XMLResponseHandler.java:367) [233:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]

	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609) [?:?]

	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) [?:?]

	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841) [?:?]

	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770) [?:?]

	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) [?:?]

	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) [?:?]

	at org.eclipse.smarthome.binding.bosesoundtouch.internal.XMLResponseProcessor.handleMessage(XMLResponseProcessor.java:45) [233:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]

	at org.eclipse.smarthome.binding.bosesoundtouch.handler.BoseSoundTouchHandler.onWebSocketText(BoseSoundTouchHandler.java:350) [233:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]

	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:189) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:158) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [82:org.eclipse.jetty.io:9.3.21.v20170918]

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [82:org.eclipse.jetty.io:9.3.21.v20170918]

	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [82:org.eclipse.jetty.io:9.3.21.v20170918]

	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [93:org.eclipse.jetty.util:9.3.21.v20170918]

	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [93:org.eclipse.jetty.util:9.3.21.v20170918]

	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [93:org.eclipse.jetty.util:9.3.21.v20170918]

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [93:org.eclipse.jetty.util:9.3.21.v20170918]

	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [93:org.eclipse.jetty.util:9.3.21.v20170918]

	at java.lang.Thread.run(Thread.java:748) [?:?]

`
***
OR
***
`2018-05-31 11:37:54.504 [WARN ] [dtouch.handler.BoseSoundTouchHandler] - Buero: Could not parse XML from string '<updates deviceID="F45EAB5C6B02"><nowPlayingUpdated><nowPlaying deviceID="YYY" source="ALEXA" sourceAccount=""><ContentItem source="ALEXA" type="tracklisturl" location="DO_NOT_RESUME" sourceAccount="" isPresetable="false"><itemName></itemName></ContentItem><track>Alexa</track><artist></artist><album></album><stationName></stationName><art artImageStatus="SHOW_DEFAULT_IMAGE" /><time total="0">60</time><skipEnabled /><playStatus>PLAY_STATE</playStatus><skipPreviousSupported value="false" /><seekSupported value="true" /><streamType>RADIO_TRACKS</streamType></nowPlaying></nowPlayingUpdated></updates>'.`

java.lang.NullPointerException: null

	at org.eclipse.smarthome.binding.bosesoundtouch.internal.ContentItem.isValid(ContentItem.java:74) [233:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]

	at org.eclipse.smarthome.binding.bosesoundtouch.internal.CommandExecutor.setCurrentContentItem(CommandExecutor.java:114) [233:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]

	at org.eclipse.smarthome.binding.bosesoundtouch.internal.XMLResponseHandler.endElement(XMLResponseHandler.java:367) [233:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]

	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) [?:?]

	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) [?:?]

	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841) [?:?]

	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770) [?:?]

	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) [?:?]

	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) [?:?]

	at org.eclipse.smarthome.binding.bosesoundtouch.internal.XMLResponseProcessor.handleMessage(XMLResponseProcessor.java:45) [233:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]

	at org.eclipse.smarthome.binding.bosesoundtouch.handler.BoseSoundTouchHandler.onWebSocketText(BoseSoundTouchHandler.java:350) [233:org.eclipse.smarthome.binding.bosesoundtouch:0.10.0.oh230]

	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:189) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:158) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511) [98:org.eclipse.jetty.websocket.common:9.3.21.v20170918]

	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [82:org.eclipse.jetty.io:9.3.21.v20170918]

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [82:org.eclipse.jetty.io:9.3.21.v20170918]

	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [82:org.eclipse.jetty.io:9.3.21.v20170918]

	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [93:org.eclipse.jetty.util:9.3.21.v20170918]

	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [93:org.eclipse.jetty.util:9.3.21.v20170918]

	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [93:org.eclipse.jetty.util:9.3.21.v20170918]

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [93:org.eclipse.jetty.util:9.3.21.v20170918]

	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [93:org.eclipse.jetty.util:9.3.21.v20170918]

	at java.lang.Thread.run(Thread.java:748) [?:?]

==> /var/log/openhab2/events.log <==

2018-05-31 11:37:54.526 [vent.ItemStateChangedEvent] - bosesoundtouch_10_F45EAB5C6B02_nowPlayingItemName changed from NULL to null`

**Comment by tratho** [comment]
@kaikreuzer this is fixed with
https://github.com/eclipse/smarthome/pull/5685

**Comment by kaikreuzer** [comment]
Excellent, thanks!

**Comment by tratho** [comment]
it's not my work, just saw it

**Comment by kaikreuzer** [comment]
That's what I meant: Thanks for seeing it ;-)
